version: 2.0.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- ps: >-
    nuget restore

    . "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.7.2 Tools\x64\sn.exe" -k ./MencoderSharp/MencoderSharp.snk
build:
  verbosity: minimal
artifacts:
- path: '**\Mencoder*.nupkg'
  name: NugetPackage
- path: MencoderSharpDemo\bin\Release
  name: DemoApplication
deploy:
- provider: GitHub
  auth_token:
    secure: b8vU0PhyLjyNdrWX81bl3FeKGgzw9OuRRr8kKpy3vxjZNmpTahsIY6JjVGxJzV0M
- provider: NuGet
  api_key:
    secure: uam/dXnhJv544YdAQNP+mKC9fkL7UFQydK/55TWjozWEswDWNUBh/Mq/WLv8Fa8U